### ISSUE TITLE
Half a sentence without context

### ISSUE THREAD

**Issue by theFeu** [Icinga/icingaweb2-module-training#6]
[...] Um den Installationswizard benutzen zu dürfen ist aus Sicherheitsgründen ein Token erforderlich. **Man wird von der Weboberfläche** Damit stellen wir sicher, dass es zwischen Installation und Einrichtung nie einen Zeitpunkt gibt, zu welchem ein Angreifer eine Umgebung übernehmen könnte. [...]

Can this be removed or should the rest of the sentence be added?

**Comment by lippserd** [comment]
Please add the rest of the sentence.
